-- 盈利汇总数据
CREATE TABLE IF NOT EXISTS DEPOSIT (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  DATE TEXT(10) NOT NULL,
  FUND_DAY_INCOME CHAR(20) NOT NULL,
  STOCK_DAY_INCOME CHAR(20) NOT NULL,
  DAY_INCOME CHAR(20) NOT NULL,
  FUND_MARKET_VALUE CHAR(20) NOT NULL,
  STOCK_MARKET_VALUE CHAR(20) NOT NULL,
  TOTAL_MARKET_VALUE CHAR(20) NOT NULL,
  BIG_MARKET_CHANGE_PERCENT CHAR(20) NULL,
  BIG_MARKET_VALUE CHAR(20) NULL,
  USERNAME varchar(50) NOT NULL
);
CREATE INDEX IF NOT EXISTS IDX_DEPOSIT_USERNAME ON DEPOSIT(USERNAME);

-- 基金数据
CREATE TABLE IF NOT EXISTS FUND (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT(10) NOT NULL,
  NAME TEXT(100),
  COST_PRICE CHAR(20) NOT NULL,
  BONDS CHAR(30) NOT NULL,
  APP CHAR(10) NOT NULL,
  HIDE INTEGER,
  USERNAME varchar(50) NOT NULL
);

-- 基金历史数据
CREATE TABLE IF NOT EXISTS FUND_HIS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT(10) NOT NULL,
  NAME TEXT(100),
  COST_PRICE CHAR(20) NOT NULL,
  BONDS CHAR(30) NOT NULL,
  APP CHAR(10) NOT NULL,
  HIDE INTEGER,
  CREATE_DATE DATETIME,
  USERNAME varchar(50) NOT NULL
);

-- 基金净值数据
CREATE TABLE IF NOT EXISTS FUND_JZ (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT(10) NOT NULL,
  FSRQ CHAR(30),
  DWJZ CHAR(30)
);

-- 股票数据
CREATE TABLE IF NOT EXISTS STOCK (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT(10) NOT NULL,
  NAME TEXT(100),
  COST_PRICE CHAR(20) NOT NULL,
  BONDS INT NOT NULL,
  APP CHAR(10) NOT NULL,
  HIDE INTEGER,
  USERNAME varchar(50) NOT NULL
);

-- 股票历史数据
CREATE TABLE IF NOT EXISTS STOCK_HIS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT(10) NOT NULL,
  NAME TEXT(100),
  COST_PRICE CHAR(20) NOT NULL,
  BONDS INT NOT NULL,
  APP CHAR(10) NOT NULL,
  HIDE INTEGER,
  CREATE_DATE DATETIME,
  USERNAME varchar(50) NOT NULL
);

-- 字典数据
CREATE TABLE IF NOT EXISTS PARAM (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TYPE TEXT(10) NOT NULL,
  CODE CHAR(20) NOT NULL,
  NAME INT NOT NULL,
  USERNAME varchar(50) NOT NULL
);
CREATE INDEX IF NOT EXISTS IDX_PARAM_TYPE ON PARAM(TYPE);
CREATE INDEX IF NOT EXISTS IDX_PARAM_USERNAME ON PARAM(USERNAME);

-- 买卖数据
CREATE TABLE IF NOT EXISTS BUY_OR_SELL (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  DATE TEXT(10) NOT NULL,
  CODE TEXT(10) NOT NULL,
  TYPE CHAR(2) NOT NULL,
  PRICE CHAR(20) NOT NULL,
  COST CHAR(20),
  BONDS CHAR(20) NOT NULL,
  INCOME CHAR(20) NOT NULL,
  OPENPRICE CHAR(20) NOT NULL,
  USERNAME varchar(50) NOT NULL
);

-- 交易日数据
CREATE TABLE IF NOT EXISTS OPEN_PERSISTENT_MONTH (
  MONTH TEXT(10) PRIMARY KEY NOT NULL,
  DATA TEXT(512) NOT NULL
);

-- 注意：已经移除 users 和 authorities 表的创建